/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Alertas.ErrorAlerta;
import Alertas.WarningAlerta;
import Controller.ReportesController;
import Controller.loginController;
import Modal.modalUsuario;
import javax.swing.ListSelectionModel;
import util.Memoria;

/**
 *
 * @author Lenovo
 */
public class UsuarioView extends javax.swing.JInternalFrame {

    loginController lc = new loginController();
    ReportesController rc = new ReportesController();
    //private List<modalUsuario> usuarioList = null;

    /**
     * Creates new form CategoriaView
     *
     */
    public UsuarioView() {
        initComponents();
        //this.setUI(null);
        tblUsuario.getTableHeader().setDefaultRenderer(new util.EstiloTablaHeader());
        tblUsuario.setDefaultRenderer(String.class, new util.EstiloTablaRenderer());
        tblUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblUsuario.getColumnModel().getColumn(11).setMaxWidth(0);
        tblUsuario.getColumnModel().getColumn(11).setMinWidth(0);
        tblUsuario.getColumnModel().getColumn(11).setPreferredWidth(0);

        tblUsuario.getColumnModel().getColumn(0).setMaxWidth(0);
        tblUsuario.getColumnModel().getColumn(0).setMinWidth(0);
        tblUsuario.getColumnModel().getColumn(0).setPreferredWidth(0);
        lc.ListarUsuarios(tblUsuario, "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlusuarios = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        rSPanelImage5 = new rojerusan.RSPanelImage();
        jSeparator2 = new javax.swing.JSeparator();
        txtbuscar = new app.bolivia.swing.JCTextField();
        btn3 = new rojeru_san.RSButtonRiple();
        btnAgregar = new rojeru_san.RSButtonRiple();
        btnEliminar = new rojeru_san.RSButtonRiple();
        btnActualizar = new rojeru_san.RSButtonRiple();
        btnActualizar1 = new rojeru_san.RSButtonRiple();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Usuarios");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_user_group_man_woman_48px.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1449, 900));
        setVisible(true);

        pnlusuarios.setBackground(new java.awt.Color(255, 255, 255));

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        rSPanelImage5.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelImage5.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar_1.png"))); // NOI18N
        rSPanelImage5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(0, 112, 192));
        rSPanelImage5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 47, 180, 20));

        txtbuscar.setBorder(null);
        txtbuscar.setToolTipText("");
        txtbuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtbuscar.setPhColor(new java.awt.Color(0, 112, 192));
        txtbuscar.setPlaceholder("Dni/Apellido...");
        txtbuscar.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        rSPanelImage5.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 8, 140, 40));

        btn3.setBackground(new java.awt.Color(255, 255, 255));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn-cerrar.png"))); // NOI18N
        btn3.setColorHover(new java.awt.Color(31, 174, 255));
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn3MouseReleased(evt);
            }
        });
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        rSPanelImage5.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 8, 35, 35));

        btnAgregar.setBackground(new java.awt.Color(33, 169, 56));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar1.png"))); // NOI18N
        btnAgregar.setText("Nuevo");
        btnAgregar.setToolTipText("");
        btnAgregar.setColorHover(new java.awt.Color(0, 198, 56));
        btnAgregar.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar2.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(200, 35, 51));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eleminar1.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setColorHover(new java.awt.Color(238, 35, 51));
        btnEliminar.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar2.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnActualizar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnActualizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar1.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnActualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/print1.png"))); // NOI18N
        btnActualizar1.setText("Imprimir");
        btnActualizar1.setToolTipText("Imprimir Informacion \nDel Usuario");
        btnActualizar1.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnActualizar1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnActualizar1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/print2.png"))); // NOI18N
        btnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSPanelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSPanelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista De Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        tblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", null, null, null, null, null, null, null, null, null, null, null},
                {"1", null, null, null, null, null, null, null, null, null, null, null},
                {"0", null, null, null, null, null, null, null, null, null, null, null},
                {"0", null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "APELLIDO", "USUARIO", "CONTRASEÑA", "DNI", "FECHA", "CEL/TEL", "GENERO", "ESTADO", "CARGO", "FOTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuario.setGridColor(new java.awt.Color(0, 0, 0));
        tblUsuario.setRowHeight(20);
        tblUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblUsuarioKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tblUsuario);

        jPanel1.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlusuariosLayout = new javax.swing.GroupLayout(pnlusuarios);
        pnlusuarios.setLayout(pnlusuariosLayout);
        pnlusuariosLayout.setHorizontalGroup(
            pnlusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlusuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlusuariosLayout.setVerticalGroup(
            pnlusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlusuariosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlusuarios, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (tblUsuario.getSelectedRow() > -1) {
            tblUsuario.removeRowSelectionInterval(tblUsuario.getSelectedRow(), tblUsuario.getSelectedRow());
        }
        Memoria.put("accion", loginController.CRUD_NUEVO);
        accionesUser view = new accionesUser(null, true);
        view.setVisible(true);
        lc.ListarUsuarios(tblUsuario, "");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (tblUsuario.getRowCount() > 0) {
            if (tblUsuario.getSelectedRowCount() > 0) {

                modalUsuario iduser = new modalUsuario();
                int codigo = (int) tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 0);
                iduser.setIdUsuario(codigo);

                Memoria.put("iduser", iduser);
                WarningAlerta wa = new WarningAlerta(null, true);
                wa.setVisible(true);
                lc.ListarUsuarios(tblUsuario, "");

                //WarningAlerta.lblMensaje2.setText("¡¡¡COMPLETE TODOS LOS CAMPOS!!!");
                //ErrorAlerta ae = new ErrorAlerta(null, true);
                //ErrorAlerta.lblMensaje2.setText("¡¡¡COMPLETE TODOS LOS CAMPOS!!!");
                //ae.setVisible(true);
            } else {

                ErrorAlerta ae = new ErrorAlerta(null, true);
                ErrorAlerta.lblMensaje2.setText("¡¡¡SELECCIONE UN USUARIO!!!");
                ae.setVisible(true);
            }
        } else {
            ErrorAlerta ae = new ErrorAlerta(null, true);
            ErrorAlerta.lblMensaje2.setText("¡¡¡NO HAY USUARIOS!!!");
            ae.setVisible(true);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        if (tblUsuario.getRowCount() > 0) {
            if (tblUsuario.getSelectedRowCount() > 0) {
                int idUsuario = (int) tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 0);
                String apellido = (String) tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 2);
                String nombre = (String) tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 1);
                int dni = (int) tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 5);
                int telefono = (int) tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 7);
                String usuario = (String) tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 3);
                String clave = (String) tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 4);
                String sexo = (String) tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 8);
                String fotoUrl = (String) tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 11);
                String rols = (String) tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 10);
                String estadoS = (String) tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 9);

                modalUsuario mu = new modalUsuario(idUsuario, apellido, nombre, dni, telefono, usuario, clave, sexo, fotoUrl, rols, estadoS);
//
                Memoria.put("accion", loginController.CRUD_EDITAR);
                Memoria.put("mu", mu);
                accionesUser view = new accionesUser(null, true);

                view.setVisible(true);
                lc.ListarUsuarios(tblUsuario, "");

            } else {

                ErrorAlerta ae = new ErrorAlerta(null, true);
                ErrorAlerta.lblMensaje2.setText("¡¡¡SELECCIONE UN USUARIO!!!");
                ae.setVisible(true);
            }
        } else {
            ErrorAlerta ae = new ErrorAlerta(null, true);
            ErrorAlerta.lblMensaje2.setText("¡¡¡NO HAY USUARIOS!!!");
            ae.setVisible(true);
        }


    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
        if (tblUsuario.getRowCount() > 0) {
            if (tblUsuario.getSelectedRowCount() > 0) {

                int codigo = (int) tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 0);
                String fotoUrl = (String) tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 11);
                System.out.println("codigo: " + codigo);

                rc.ReporteUsuario(codigo);
                //ErrorAlerta ae = new ErrorAlerta(null, true);
                //ErrorAlerta.lblMensaje2.setText("¡¡¡COMPLETE TODOS LOS CAMPOS!!!");
                //ae.setVisible(true);

            } else {

                ErrorAlerta ae = new ErrorAlerta(null, true);
                ErrorAlerta.lblMensaje2.setText("¡¡¡SELECCIONE UN USUARIO!!!");
                ae.setVisible(true);
            }
        } else {
            ErrorAlerta ae = new ErrorAlerta(null, true);
            ErrorAlerta.lblMensaje2.setText("¡¡¡NO HAY USUARIOS!!!");
            ae.setVisible(true);
        }

        // System.out.println("codiog: 123456" );
    }//GEN-LAST:event_btnActualizar1ActionPerformed

    private void tblUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblUsuarioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblUsuarioKeyReleased

    private void btn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3MouseEntered

    private void btn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3MouseExited

    private void btn3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3MousePressed

    private void btn3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3MouseReleased

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        txtbuscar.setText("");
        txtbuscar.requestFocus();
        lc.ListarUsuarios(tblUsuario, "");
    }//GEN-LAST:event_btn3ActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        if (tblUsuario.getSelectedRow() > -1) {
            tblUsuario.removeRowSelectionInterval(tblUsuario.getSelectedRow(), tblUsuario.getSelectedRow());
        }
        lc.ListarUsuarios(tblUsuario, "");
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        if (tblUsuario.getSelectedRow() > -1) {
            tblUsuario.removeRowSelectionInterval(tblUsuario.getSelectedRow(), tblUsuario.getSelectedRow());
        }
        String busca = txtbuscar.getText();
        lc.ListarUsuarios(tblUsuario, busca);
    }//GEN-LAST:event_txtbuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btn3;
    private rojeru_san.RSButtonRiple btnActualizar;
    private rojeru_san.RSButtonRiple btnActualizar1;
    private rojeru_san.RSButtonRiple btnAgregar;
    private rojeru_san.RSButtonRiple btnEliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnlusuarios;
    private rojerusan.RSPanelImage rSPanelImage5;
    private javax.swing.JTable tblUsuario;
    private app.bolivia.swing.JCTextField txtbuscar;
    // End of variables declaration//GEN-END:variables

}
