/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Alertas.ErrorAlerta;
import Alertas.ExitoAlerta;
import Controller.loginController;
import Modal.modalUsuario;
import java.io.File;
import java.io.IOException;
import java.nio.file.CopyOption;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import util.Memoria;

/**
 *
 * @author Lenovo
 */
public class accionesUser extends javax.swing.JDialog {

    JFileChooser foto = new JFileChooser();
    File archivo;
    String ruta_guardar = "./imagenes/";
    String origen;

    private String accion;
    modalUsuario user = new modalUsuario();
    loginController lc = new loginController();
    modalUsuario mu = (modalUsuario) Memoria.get("mu");

    /**
     * Creates new form accionesUser
     *
     * @param parent
     * @param modal
     */
    public accionesUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // user = new modalUsuario();
        this.setLocationRelativeTo(null);
        recogerDatos();
        txtNombre.requestFocus();
    }

    private void recogerDatos() {

        accion = Memoria.get("accion").toString();
        //this.setTitle(accion + " USER");
        //  lblTitulo.setText(accion + " USER");
        if (accion.equals("Registrar")) {
            btnAccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar1.png")));
            btnAccion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar2.png")));

        } else {

            btnAccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png")));
            btnAccion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar1.png")));

            txtNombre.setText(mu.getNombre());
            txtApellido.setText(mu.getApellido());
            txtDni.setText(mu.getDni() + "");
            txtTelefono.setText(mu.getTelefono() + "");
            cboEstado.setSelectedItem(mu.getEstadoS());
            cboSexo.setSelectedItem(mu.getSexo());
            txtUsuario.setText(mu.getUsuario());
            txtContraseña.setText(mu.getClave());
            cboRol.setSelectedItem(mu.getRols());
            lblFoto.setIcon(new ImageIcon("./imagenes/" + mu.getFotoUrl()));

            //mu.setClave(txtContraseña.getText());
            //mu.setIdrol(cboRol.getSelectedIndex());
        }
        btnAccion.setText(accion);

        //user = (modalUsuario) Memoria.get("user");
        // Memoria.put("seccion", null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new rojerusan.RSMetroTextFullPlaceHolder();
        txtApellido = new rojerusan.RSMetroTextFullPlaceHolder();
        cboSexo = new rojerusan.RSComboMetro();
        txtDni = new rojerusan.RSMetroTextFullPlaceHolder();
        cboRol = new rojerusan.RSComboMetro();
        txtUsuario = new rojerusan.RSMetroTextFullPlaceHolder();
        txtContraseña = new rojerusan.RSMetroTextPassPlaceHolderView();
        cboEstado = new rojerusan.RSComboMetro();
        lblFoto = new rojerusan.RSLabelImage();
        btnCargar = new rojeru_san.RSButtonRiple();
        txtTelefono = new rojerusan.RSMetroTextFullPlaceHolder();
        jPanel3 = new javax.swing.JPanel();
        btnActualizar = new rojeru_san.RSButtonRiple();
        btnAccion = new rojeru_san.RSButtonRiple();
        btnCancelar = new rojeru_san.RSButtonRiple();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setBorderColor(new java.awt.Color(31, 174, 255));
        txtNombre.setBotonColor(new java.awt.Color(31, 174, 255));
        txtNombre.setPlaceholder("Nombre...");
        txtNombre.setSoloLetras(true);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtApellido.setBorderColor(new java.awt.Color(31, 174, 255));
        txtApellido.setBotonColor(new java.awt.Color(31, 174, 255));
        txtApellido.setPlaceholder("Apellido...");
        txtApellido.setSoloLetras(true);

        cboSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " Genero", "Hombre", "Mujer" }));
        cboSexo.setColorArrow(new java.awt.Color(31, 174, 255));
        cboSexo.setColorBorde(new java.awt.Color(31, 174, 255));
        cboSexo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboSexo.setMinimumSize(new java.awt.Dimension(101, 28));
        cboSexo.setPreferredSize(new java.awt.Dimension(200, 41));

        txtDni.setForeground(new java.awt.Color(0, 0, 0));
        txtDni.setBorderColor(new java.awt.Color(31, 174, 255));
        txtDni.setBotonColor(new java.awt.Color(31, 174, 255));
        txtDni.setPlaceholder("DNI...");
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniKeyTyped(evt);
            }
        });

        cboRol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " Cargo", "Administrador", "Empleado" }));
        cboRol.setColorArrow(new java.awt.Color(31, 174, 255));
        cboRol.setColorBorde(new java.awt.Color(31, 174, 255));
        cboRol.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboRol.setMinimumSize(new java.awt.Dimension(101, 28));
        cboRol.setPreferredSize(new java.awt.Dimension(200, 41));

        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario.setBorderColor(new java.awt.Color(31, 174, 255));
        txtUsuario.setBotonColor(new java.awt.Color(31, 174, 255));
        txtUsuario.setPlaceholder("Usuario...");

        txtContraseña.setForeground(new java.awt.Color(0, 0, 0));
        txtContraseña.setBorderColor(new java.awt.Color(31, 174, 255));
        txtContraseña.setBotonColor(new java.awt.Color(31, 174, 255));
        txtContraseña.setPlaceholder("Contraseña...");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  Estado", "Activo", "Desactivo" }));
        cboEstado.setColorArrow(new java.awt.Color(31, 174, 255));
        cboEstado.setColorBorde(new java.awt.Color(31, 174, 255));
        cboEstado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboEstado.setMinimumSize(new java.awt.Dimension(101, 28));
        cboEstado.setPreferredSize(new java.awt.Dimension(200, 41));
        cboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstadoActionPerformed(evt);
            }
        });

        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 174, 255), 3));
        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user-prueba.png"))); // NOI18N

        btnCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_pictures_folder_48px.png"))); // NOI18N
        btnCargar.setText("CARGAR");
        btnCargar.setToolTipText("");
        btnCargar.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnCargar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setBorderColor(new java.awt.Color(31, 174, 255));
        txtTelefono.setBotonColor(new java.awt.Color(31, 174, 255));
        txtTelefono.setPlaceholder("Celular/Telefono...");
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 24, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(cboRol, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 24, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 24, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(9, 9, 9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 24, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        btnActualizar.setToolTipText("Limpiar Campos");
        btnActualizar.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnActualizar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnActualizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar1.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnAccion.setBackground(new java.awt.Color(33, 169, 56));
        btnAccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar1.png"))); // NOI18N
        btnAccion.setText("Nuevo");
        btnAccion.setToolTipText("");
        btnAccion.setColorHover(new java.awt.Color(0, 198, 56));
        btnAccion.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnAccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAccion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar2.png"))); // NOI18N
        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(200, 35, 51));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar1.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setColorHover(new java.awt.Color(238, 35, 51));
        btnCancelar.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        //lblMensaje.setText("");
    }//GEN-LAST:event_txtNombreKeyReleased

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG", "jpg", "png");

        foto.setFileFilter(filtro);
        foto.setAcceptAllFileFilterUsed(false);
        int respuesta = foto.showOpenDialog(this);
        if (respuesta == JFileChooser.APPROVE_OPTION) {

            archivo = foto.getSelectedFile();

            if (archivo != null) {
                origen = archivo.getPath();

                ImageIcon icon = new ImageIcon(origen);
                lblFoto.setIcon(icon);

            } else {

                System.out.println("error");
            }
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void cboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEstadoActionPerformed

    private void btnAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionActionPerformed
        if (accion.equals("Registrar")) {

            boolean com = false;

            if (txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty() || txtDni.getText().isEmpty() || txtTelefono.getText().isEmpty() || txtUsuario.getText().isEmpty()
                    || txtContraseña.getText().isEmpty() || cboSexo.getSelectedIndex() == 0 || cboEstado.getSelectedIndex() == 0 || cboRol.getSelectedIndex() == 0) {
                ErrorAlerta ae = new ErrorAlerta(null, true);
                ErrorAlerta.lblMensaje2.setText("¡¡¡COMPLETE TODOS LOS CAMPOS!!!");
                ae.setVisible(true);

                txtNombre.requestFocus();
            } else {
                if (archivo == null) {
                    com = false;
                    user.setFotoUrl("user-prueba.png");
                } else {
                    com = true;
                    user.setFotoUrl(archivo.getName());

                }
                user.setNombre(txtNombre.getText());
                user.setApellido(txtApellido.getText());
                user.setDni(Integer.parseInt(txtDni.getText()));
                user.setTelefono(Integer.parseInt(txtTelefono.getText()));
                user.setEstado(cboEstado.getSelectedIndex());
                user.setSexo(cboSexo.getSelectedItem().toString());
                user.setUsuario(txtUsuario.getText());
                user.setClave(txtContraseña.getText());
                user.setIdrol(cboRol.getSelectedIndex());

                if (lc.sql_insertUsuario(user)) {

                    if (com) {
                        copyImagen(archivo.getPath(), ruta_guardar + archivo.getName());
                    }
                    ExitoAlerta ae = new ExitoAlerta(null, true);
                    ExitoAlerta.lblMensaje1.setText("¡¡¡USUARIO!!!");
                    ExitoAlerta.lblMensaje2.setText("¡¡¡REGISTRADO CON EXITO!!!");
                    ae.setVisible(true);
                    dispose();

                } else {
                    ErrorAlerta ae = new ErrorAlerta(null, true);
                    ErrorAlerta.lblMensaje2.setText("¡¡¡USUARIO NO REGISTRADO!!!");
                    ae.setVisible(true);
                }

            }
        } else {

            boolean com = false;

            if (txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty() || txtDni.getText().isEmpty() || txtTelefono.getText().isEmpty() || txtUsuario.getText().isEmpty()
                    || txtContraseña.getText().isEmpty() || cboSexo.getSelectedIndex() == 0 || cboEstado.getSelectedIndex() == 0 || cboRol.getSelectedIndex() == 0) {
                ErrorAlerta ae = new ErrorAlerta(null, true);
                ErrorAlerta.lblMensaje2.setText("¡¡¡COMPLETE TODOS LOS CAMPOS!!!");
                ae.setVisible(true);

                txtNombre.requestFocus();
            } else {
                if (archivo == null) {
                    com = false;
                    user.setFotoUrl(mu.getFotoUrl());
                } else {
                    com = true;
                    user.setFotoUrl(archivo.getName());

                }
                user.setIdUsuario(mu.getIdUsuario());
                user.setNombre(txtNombre.getText());
                user.setApellido(txtApellido.getText());
                user.setDni(Integer.parseInt(txtDni.getText()));
                user.setTelefono(Integer.parseInt(txtTelefono.getText()));
                user.setEstado(cboEstado.getSelectedIndex());
                user.setSexo(cboSexo.getSelectedItem().toString());
                user.setUsuario(txtUsuario.getText());
                user.setClave(txtContraseña.getText());
                user.setIdrol(cboRol.getSelectedIndex());

                if (lc.sql_updatetUsuario(user)) {

                    if (com) {
                        copyImagen(archivo.getPath(), ruta_guardar + archivo.getName());
                    }
                    ExitoAlerta ae = new ExitoAlerta(null, true);
                    ExitoAlerta.lblMensaje1.setText("¡¡¡USUARIO!!!");
                    ExitoAlerta.lblMensaje2.setText("¡¡¡ACTUALIZADO CON EXITO!!!");
                    ae.setVisible(true);
                    dispose();

                } else {
                    ErrorAlerta ae = new ErrorAlerta(null, true);
                    ErrorAlerta.lblMensaje2.setText("¡¡¡USUARIO NO ACTUALIZADO!!!");
                    ae.setVisible(true);
                }

            }

        }
    }//GEN-LAST:event_btnAccionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        txtApellido.setText("");
        txtContraseña.setText("");
        txtDni.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        txtUsuario.setText("");
        cboEstado.setSelectedIndex(0);
        cboRol.setSelectedIndex(0);
        cboSexo.setSelectedIndex(0);
        archivo = null;
        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user-prueba.png")));
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyTyped
        char num = evt.getKeyChar();

        if ((num < '0' || num > '8') || txtDni.getText().length() == 8) {

            evt.consume();
        }
    }//GEN-LAST:event_txtDniKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
          char num = evt.getKeyChar();

        if ((num < '0' || num > '9') || txtTelefono.getText().length() == 9) {

            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped
    public void copyImagen(String origen, String destino) {
        Path DE = Paths.get(origen);
        Path A = Paths.get(destino);

        CopyOption[] opciones = new CopyOption[]{
            StandardCopyOption.REPLACE_EXISTING,
            StandardCopyOption.COPY_ATTRIBUTES
        };

        try {
            Files.copy(DE, A, opciones);
        } catch (IOException ex) {
            Logger.getLogger(accionesUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accionesUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accionesUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accionesUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accionesUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                accionesUser dialog = new accionesUser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnAccion;
    private rojeru_san.RSButtonRiple btnActualizar;
    private rojeru_san.RSButtonRiple btnCancelar;
    private rojeru_san.RSButtonRiple btnCargar;
    private rojerusan.RSComboMetro cboEstado;
    private rojerusan.RSComboMetro cboRol;
    private rojerusan.RSComboMetro cboSexo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private rojerusan.RSLabelImage lblFoto;
    private rojerusan.RSMetroTextFullPlaceHolder txtApellido;
    private rojerusan.RSMetroTextPassPlaceHolderView txtContraseña;
    private rojerusan.RSMetroTextFullPlaceHolder txtDni;
    private rojerusan.RSMetroTextFullPlaceHolder txtNombre;
    private rojerusan.RSMetroTextFullPlaceHolder txtTelefono;
    private rojerusan.RSMetroTextFullPlaceHolder txtUsuario;
    // End of variables declaration//GEN-END:variables
}
