/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Alertas.ErrorAlerta;
import Alertas.WarningAlertaSalir;
import Modal.modalUsuario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.Timer;
import rojerusan.RSButtonHover;
import util.ImagenFondo;
import util.Memoria;

/**
 *
 * @author Bengy Aguila Ruiz bengyjar1998@outlook.com
 */
public class FormMenuPrincipal extends javax.swing.JFrame {

    Date sistemaFech;
    SimpleDateFormat formato2 = new SimpleDateFormat("dd MMMM yyyy");
    modalUsuario u = (modalUsuario) Memoria.get("modalUsuario");
    

    public FormMenuPrincipal() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage());
        //tblUsuario.setDefaultRenderer(Object.class, new modiTabla());
        setExtendedState(MAXIMIZED_BOTH);
        setDefaultCloseOperation(WarningAlertaSalir.DISPOSE_ON_CLOSE);
        pnlContenedor.setVisible(true);
        escritorio.setBorder(new ImagenFondo());
        //modalUsuario u = (modalUsuario) Memoria.get("modalUsuario");

        this.lblFoto.setImagen(new ImageIcon("./imagenes/" + u.getFotoUrl()));
        lblUser.setText("User: " + u.getUsuario());
        lblAdmin.setText("" + u.getRols());
        //cargarFormulario(UsuarioView.class);
        //  jLabel33.setVisible(false);
        //btnGastos.setVisible(false);
        jLabel38.setVisible(false);
        btnExportBD.setVisible(false);
        btnImportarBD.setVisible(false);
        System.out.println("" + u.getRols() + "-" + u.getIdrol());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlDesboard = new javax.swing.JPanel();
        btnUsuario = new rojerusan.RSButtonHover();
        btnInicio = new rojerusan.RSButtonHover();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnImportarBD = new rojerusan.RSButtonHover();
        btnReportes = new rojerusan.RSButtonHover();
        btnVender = new rojerusan.RSButtonHover();
        btnClientes = new rojerusan.RSButtonHover();
        btnProductos = new rojerusan.RSButtonHover();
        btnCategorias = new rojerusan.RSButtonHover();
        jLabel6 = new javax.swing.JLabel();
        btnUnidadMedida = new rojerusan.RSButtonHover();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        btnExportBD = new rojerusan.RSButtonHover();
        lblUser = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblFoto = new rojerusan.RSPanelImage();
        pnlCabecera = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        btnMinimizar = new rojeru_san.RSButtonRiple();
        btnExit = new rojeru_san.RSButtonRiple();
        pnlContenedor = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema De Gestion MiNilda");
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlDesboard.setOpaque(false);
        pnlDesboard.setPreferredSize(new java.awt.Dimension(250, 970));
        pnlDesboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUsuario.setBackground(new java.awt.Color(240, 240, 240));
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_user_group_man_woman_48px.png"))); // NOI18N
        btnUsuario.setText("Usuario");
        btnUsuario.setColorHover(new java.awt.Color(31, 174, 255));
        btnUsuario.setColorText(new java.awt.Color(0, 0, 0));
        btnUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        pnlDesboard.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 249, 50));

        btnInicio.setBackground(new java.awt.Color(31, 174, 255));
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_pane_48px.png"))); // NOI18N
        btnInicio.setText("Cerrar sesión");
        btnInicio.setColorHover(new java.awt.Color(3, 148, 255));
        btnInicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        pnlDesboard.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 249, 45));

        jLabel2.setBackground(new java.awt.Color(62, 126, 188));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INVENTARIO");
        jLabel2.setOpaque(true);
        pnlDesboard.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 415, 249, 30));

        jLabel4.setBackground(new java.awt.Color(62, 126, 188));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("USUARIO");
        jLabel4.setOpaque(true);
        pnlDesboard.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 249, 30));

        btnImportarBD.setBackground(new java.awt.Color(240, 240, 240));
        btnImportarBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_database_restore_48px.png"))); // NOI18N
        btnImportarBD.setText("Importar BD");
        btnImportarBD.setColorHover(new java.awt.Color(31, 174, 255));
        btnImportarBD.setColorText(new java.awt.Color(0, 0, 0));
        btnImportarBD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnImportarBD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnImportarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarBDActionPerformed(evt);
            }
        });
        pnlDesboard.add(btnImportarBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 895, 249, 45));

        btnReportes.setBackground(new java.awt.Color(240, 240, 240));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_business_report_48px.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setColorHover(new java.awt.Color(31, 174, 255));
        btnReportes.setColorText(new java.awt.Color(0, 0, 0));
        btnReportes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        pnlDesboard.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 249, 45));

        btnVender.setBackground(new java.awt.Color(240, 240, 240));
        btnVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_sell_stock_48px.png"))); // NOI18N
        btnVender.setText("Vender");
        btnVender.setColorHover(new java.awt.Color(31, 174, 255));
        btnVender.setColorText(new java.awt.Color(0, 0, 0));
        btnVender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });
        pnlDesboard.add(btnVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 249, 45));

        btnClientes.setBackground(new java.awt.Color(240, 240, 240));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_commercial_development_management_48px_1.png"))); // NOI18N
        btnClientes.setText("Cliente");
        btnClientes.setColorHover(new java.awt.Color(31, 174, 255));
        btnClientes.setColorText(new java.awt.Color(0, 0, 0));
        btnClientes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        pnlDesboard.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 249, 45));

        btnProductos.setBackground(new java.awt.Color(240, 240, 240));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/products.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setColorHover(new java.awt.Color(31, 174, 255));
        btnProductos.setColorText(new java.awt.Color(0, 0, 0));
        btnProductos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        pnlDesboard.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 445, 249, 45));

        btnCategorias.setBackground(new java.awt.Color(240, 240, 240));
        btnCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_bulleted_list_48px.png"))); // NOI18N
        btnCategorias.setText("Categorias");
        btnCategorias.setColorHover(new java.awt.Color(31, 174, 255));
        btnCategorias.setColorText(new java.awt.Color(0, 0, 0));
        btnCategorias.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCategorias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });
        pnlDesboard.add(btnCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 249, 45));

        jLabel6.setBackground(new java.awt.Color(62, 126, 188));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CLIENTES");
        jLabel6.setOpaque(true);
        pnlDesboard.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 249, 30));

        btnUnidadMedida.setBackground(new java.awt.Color(240, 240, 240));
        btnUnidadMedida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_scales_48px.png"))); // NOI18N
        btnUnidadMedida.setText("U.Medida");
        btnUnidadMedida.setColorHover(new java.awt.Color(31, 174, 255));
        btnUnidadMedida.setColorText(new java.awt.Color(0, 0, 0));
        btnUnidadMedida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUnidadMedida.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnidadMedidaActionPerformed(evt);
            }
        });
        pnlDesboard.add(btnUnidadMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 535, 249, 45));

        jLabel33.setBackground(new java.awt.Color(62, 126, 188));
        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("VENTAS");
        jLabel33.setOpaque(true);
        pnlDesboard.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 249, 30));

        jLabel34.setBackground(new java.awt.Color(62, 126, 188));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("REPORTES");
        jLabel34.setOpaque(true);
        pnlDesboard.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 249, 30));

        jLabel38.setBackground(new java.awt.Color(62, 126, 188));
        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("BASE DE DATOS");
        jLabel38.setOpaque(true);
        pnlDesboard.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 820, 249, 30));

        btnExportBD.setBackground(new java.awt.Color(240, 240, 240));
        btnExportBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_database_export_48px.png"))); // NOI18N
        btnExportBD.setText("Exportar BD");
        btnExportBD.setColorHover(new java.awt.Color(31, 174, 255));
        btnExportBD.setColorText(new java.awt.Color(0, 0, 0));
        btnExportBD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExportBD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnExportBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportBDActionPerformed(evt);
            }
        });
        pnlDesboard.add(btnExportBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 850, 249, 45));

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setText("USER: AGUILA RUIZ");
        pnlDesboard.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 250, 30));

        lblAdmin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdmin.setText("ADMIN");
        pnlDesboard.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 40));

        lblFoto.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user-prueba.png"))); // NOI18N

        javax.swing.GroupLayout lblFotoLayout = new javax.swing.GroupLayout(lblFoto);
        lblFoto.setLayout(lblFotoLayout);
        lblFotoLayout.setHorizontalGroup(
            lblFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        lblFotoLayout.setVerticalGroup(
            lblFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        pnlDesboard.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 190));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Sistema De Gestion MiNilda");
        jLabel32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel32.setOpaque(true);

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn-minimizar.png"))); // NOI18N
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(200, 35, 51));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn-cerrar.png"))); // NOI18N
        btnExit.setColorHover(new java.awt.Color(238, 35, 51));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCabeceraLayout = new javax.swing.GroupLayout(pnlCabecera);
        pnlCabecera.setLayout(pnlCabeceraLayout);
        pnlCabeceraLayout.setHorizontalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlCabeceraLayout.setVerticalGroup(
            pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlCabeceraLayout.createSequentialGroup()
                .addGroup(pnlCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenedor.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 919, Short.MAX_VALUE)
        );

        pnlContenedor.add(escritorio, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlDesboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCabecera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlDesboard, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportBDActionPerformed
        colorhover(btnExportBD, btnUsuario, btnCategorias, btnCategorias, btnUnidadMedida, btnProductos, btnClientes, btnVender, btnImportarBD, btnReportes);
    }//GEN-LAST:event_btnExportBDActionPerformed

    private void btnUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnidadMedidaActionPerformed

        if ((u.getRols().equals("SuperAdmin") && u.getIdrol() == 3) || (u.getRols().equals("Administrador") && u.getIdrol() == 1)) {
            colorhover(btnUnidadMedida, btnUsuario, btnCategorias, btnCategorias, btnProductos, btnClientes, btnVender, btnReportes, btnExportBD, btnImportarBD);
            cargarFormulario(UnidadView.class);
        } else {
            ErrorAlerta ae = new ErrorAlerta(null, true);
            ErrorAlerta.lblMensaje2.setText("¡¡¡ACCESO DENEGADO!!!");
            ae.setVisible(true);
        }
    }//GEN-LAST:event_btnUnidadMedidaActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed

        if ((u.getRols().equals("SuperAdmin") && u.getIdrol() == 3) || (u.getRols().equals("Administrador") && u.getIdrol() == 1)) {
            cargarFormulario(CategoriaView.class);
            colorhover(btnCategorias, btnUsuario, btnProductos, btnProductos, btnUnidadMedida, btnClientes, btnVender, btnReportes, btnExportBD, btnImportarBD);
        } else {
            ErrorAlerta ae = new ErrorAlerta(null, true);
            ErrorAlerta.lblMensaje2.setText("¡¡¡ACCESO DENEGADO!!!");
            ae.setVisible(true);
        }
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed

        if ((u.getRols().equals("SuperAdmin") && u.getIdrol() == 3) || (u.getRols().equals("Administrador") && u.getIdrol() == 1)) {
            cargarFormulario(InventarioView.class);
            colorhover(btnProductos, btnUsuario, btnCategorias, btnCategorias, btnUnidadMedida, btnClientes, btnVender, btnReportes, btnExportBD, btnImportarBD);
        } else {
            ErrorAlerta ae = new ErrorAlerta(null, true);
            ErrorAlerta.lblMensaje2.setText("¡¡¡ACCESO DENEGADO!!!");
            ae.setVisible(true);
        }

    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        colorhover(btnClientes, btnUsuario, btnCategorias, btnCategorias, btnUnidadMedida, btnProductos, btnVender, btnReportes, btnExportBD, btnImportarBD);
        cargarFormulario(clienteView.class);

    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        colorhover(btnVender, btnUsuario, btnCategorias, btnCategorias, btnUnidadMedida, btnProductos, btnClientes, btnReportes, btnExportBD, btnImportarBD);
        cargarFormulario(ventasView.class);
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed

        if ((u.getRols().equals("SuperAdmin") && u.getIdrol() == 3) || (u.getRols().equals("Administrador") && u.getIdrol() == 1)) {
            colorhover(btnReportes, btnUsuario, btnCategorias, btnCategorias, btnUnidadMedida, btnProductos, btnClientes, btnVender, btnExportBD, btnImportarBD);
            cargarFormulario(reportesView.class);
        } else {
            ErrorAlerta ae = new ErrorAlerta(null, true);
            ErrorAlerta.lblMensaje2.setText("¡¡¡ACCESO DENEGADO!!!");
            ae.setVisible(true);
        }
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        //pnlinicio.setVisible(true);
        //colorhover(btnInicio, btnUsuario, btnReportes, btnCategorias, btnUnidadMedida, btnProductos, btnClientes, btnVender, btnExportBD, btnImportarBD);

        WarningAlertaSalir salir = new WarningAlertaSalir(this, true);
        salir.setVisible(true);

        ///this.dispose();

    }//GEN-LAST:event_btnInicioActionPerformed
    void cerrar() {
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            WarningAlertaSalir wa = new WarningAlertaSalir(this, true);
            wa.setVisible(true);
            //Confirmarsalida();

        } catch (Exception l) {
        }
    }
    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        if (u.getRols().equals("SuperAdmin") && u.getIdrol() == 3) {
            colorhover(btnUsuario, btnProductos, btnCategorias, btnCategorias, btnUnidadMedida, btnClientes, btnVender, btnReportes, btnExportBD, btnImportarBD);
            cargarFormulario(UsuarioView.class);
        } else {
            ErrorAlerta ae = new ErrorAlerta(null, true);
            ErrorAlerta.lblMensaje2.setText("¡¡¡ACCESO DENEGADO!!!");
            ae.setVisible(true);
        }


    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnImportarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarBDActionPerformed
        colorhover(btnImportarBD, btnUsuario, btnCategorias, btnCategorias, btnUnidadMedida, btnProductos, btnClientes, btnVender, btnExportBD, btnReportes);
    }//GEN-LAST:event_btnImportarBDActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setState(ICONIFIED);

    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        sistemaFech = new Date();
        formato2 = new SimpleDateFormat("dd MMMM yyyy");

        Timer tiempo = new Timer(100, new FormMenuPrincipal.hora());
        tiempo.start();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormMenuPrincipal().setVisible(true);
        });
    }

    class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Date sistemaHora = new Date();
            String pmAm = "hh:mm:ss a";
            SimpleDateFormat formato = new SimpleDateFormat(pmAm);
            Calendar now = Calendar.getInstance();

            jLabel32.setText("Sistema De Gestion De Ventas Mi Nilda" + " - " + "Fecha: " + String.format(formato.format(sistemaHora), now) + " -  Fecha: " + formato2.format(sistemaFech));

        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover btnCategorias;
    private rojerusan.RSButtonHover btnClientes;
    private rojeru_san.RSButtonRiple btnExit;
    private rojerusan.RSButtonHover btnExportBD;
    private rojerusan.RSButtonHover btnImportarBD;
    private rojerusan.RSButtonHover btnInicio;
    private rojeru_san.RSButtonRiple btnMinimizar;
    private rojerusan.RSButtonHover btnProductos;
    private rojerusan.RSButtonHover btnReportes;
    private rojerusan.RSButtonHover btnUnidadMedida;
    private rojerusan.RSButtonHover btnUsuario;
    private rojerusan.RSButtonHover btnVender;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdmin;
    private rojerusan.RSPanelImage lblFoto;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlDesboard;
    // End of variables declaration//GEN-END:variables

    private void colorhover(RSButtonHover uno, RSButtonHover dos, RSButtonHover tres, RSButtonHover cuatro, RSButtonHover cinco, RSButtonHover seis, RSButtonHover siete,
            RSButtonHover ocho, RSButtonHover nueve, RSButtonHover diez) {

        uno.setBackground(new Color(31, 174, 255));

        dos.setBackground(new Color(244, 244, 244));
        dos.setColorHover(new Color(31, 174, 255));

        tres.setBackground(new Color(244, 244, 244));
        tres.setColorHover(new Color(31, 174, 255));
        tres.setColorText(Color.BLACK);
        tres.setColorTextHover(Color.WHITE);

        cuatro.setBackground(new Color(244, 244, 244));
        cuatro.setColorHover(new Color(31, 174, 255));

        cinco.setBackground(new Color(244, 244, 244));
        cinco.setColorHover(new Color(31, 174, 255));

        seis.setBackground(new Color(244, 244, 244));
        seis.setColorHover(new Color(31, 174, 255));

        siete.setBackground(new Color(244, 244, 244));
        siete.setColorHover(new Color(31, 174, 255));

        ocho.setBackground(new Color(244, 244, 244));
        ocho.setColorHover(new Color(31, 174, 255));

        nueve.setBackground(new Color(244, 244, 244));
        nueve.setColorHover(new Color(31, 174, 255));

        diez.setBackground(new Color(244, 244, 244));
        diez.setColorHover(new Color(31, 174, 255));

    }

    private void cargarFormulario(Class<?> aClass) {
        try {
            // Variable de control
            JInternalFrame view = null;
            // Buscar formulario
            for (JInternalFrame form : escritorio.getAllFrames()) {
                if (aClass.isInstance(form)) {
                    view = form;
                    break;
                }
            }
            // Crear formulario
            if (view == null) {
                view = (JInternalFrame) Class.forName(aClass.getName()).newInstance();
                escritorio.add(view);

                Dimension desktopSize = escritorio.getSize();
                Dimension FrameSize = view.getSize();

                view.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
                //view.setMaximum(true);
                /// ((BasicInternalFrameUI) view.getUI()).setNorthPane(null);
                view.show();
            }
            view.setSelected(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
