/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Alertas.ErrorAlerta;
import Alertas.WarningAlertaI;
import Controller.ReportesController;
import Controller.inventarioController;
import Modal.modalInventario;
import javax.swing.ListSelectionModel;
import util.Memoria;

/**
 *
 * @author Bengy Aguila Ruiz bengyjar1998@outlook.com
 */
public class InventarioView extends javax.swing.JInternalFrame {

    inventarioController ic = new inventarioController();
    ReportesController rc = new ReportesController();
    //private List<modalUsuario> usuarioList = null;

    /**
     * Creates new form CategoriaView
     *
     */
    public InventarioView() {
        initComponents();
        //this.setUI(null);
        tblInventario.getTableHeader().setDefaultRenderer(new util.EstiloTablaHeader());
        tblInventario.setDefaultRenderer(Object.class, new util.EstiloTablaRendererInventario());
        tblInventario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblInventario.getColumnModel().getColumn(0).setMaxWidth(0);
        tblInventario.getColumnModel().getColumn(0).setMinWidth(0);
        tblInventario.getColumnModel().getColumn(0).setPreferredWidth(0);

        //tblInventario.getColumnModel().getColumn(1).setMaxWidth(270);
        //tblInventario.getColumnModel().getColumn(1).setMinWidth(270);
        // tblInventario.getColumnModel().getColumn(6).setMinWidth(120);
        //tblInventario.getColumnModel().getColumn(6).setMaxWidth(120);
        tblInventario.getColumnModel().getColumn(6).setPreferredWidth(20);
        tblInventario.getColumnModel().getColumn(1).setPreferredWidth(200);
        ic.ListarInventario(tblInventario, "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlusuarios = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        rSPanelImage5 = new rojerusan.RSPanelImage();
        jSeparator2 = new javax.swing.JSeparator();
        txtbuscar = new app.bolivia.swing.JCTextField();
        btn3 = new rojeru_san.RSButtonRiple();
        btnAgregar = new rojeru_san.RSButtonRiple();
        btnEliminar = new rojeru_san.RSButtonRiple();
        btnActualizar = new rojeru_san.RSButtonRiple();
        btnImprimir = new rojeru_san.RSButtonRiple();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Inventario");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/products.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1449, 900));
        setVisible(true);

        pnlusuarios.setBackground(new java.awt.Color(255, 255, 255));

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        rSPanelImage5.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelImage5.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar_1.png"))); // NOI18N
        rSPanelImage5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(0, 112, 192));
        rSPanelImage5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 47, 180, 20));

        txtbuscar.setBorder(null);
        txtbuscar.setToolTipText("");
        txtbuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtbuscar.setPhColor(new java.awt.Color(0, 112, 192));
        txtbuscar.setPlaceholder("Nombre...");
        txtbuscar.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        rSPanelImage5.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 8, 140, 40));

        btn3.setBackground(new java.awt.Color(255, 255, 255));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn-cerrar.png"))); // NOI18N
        btn3.setColorHover(new java.awt.Color(31, 174, 255));
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn3MouseReleased(evt);
            }
        });
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        rSPanelImage5.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 8, 35, 35));

        btnAgregar.setBackground(new java.awt.Color(33, 169, 56));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar1.png"))); // NOI18N
        btnAgregar.setText("Nuevo");
        btnAgregar.setToolTipText("");
        btnAgregar.setColorHover(new java.awt.Color(0, 198, 56));
        btnAgregar.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar2.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(200, 35, 51));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eleminar1.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setColorHover(new java.awt.Color(238, 35, 51));
        btnEliminar.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar2.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnActualizar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnActualizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar1.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/print1.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setToolTipText("Imprimir Informacion \nDe Todas Las Unidades\nDe Medida");
        btnImprimir.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnImprimir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnImprimir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/print2.png"))); // NOI18N
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSPanelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSPanelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista De Categorias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        tblInventario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", null, null, null, null, null, null, null, null},
                {"1", null, null, null, null, null, null, null, null},
                {"0", null, null, null, null, null, null, null, null},
                {"0", null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "PRODUCTO", "CATEGORIA", "U.MEDIDA", "P.COMPRA", "P.VENTA", "STOCK", "F.VENCIMIENTO", "DESCRIPCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblInventario.setGridColor(new java.awt.Color(0, 0, 0));
        tblInventario.setRowHeight(20);
        tblInventario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblInventarioKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tblInventario);

        jPanel1.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlusuariosLayout = new javax.swing.GroupLayout(pnlusuarios);
        pnlusuarios.setLayout(pnlusuariosLayout);
        pnlusuariosLayout.setHorizontalGroup(
            pnlusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlusuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlusuariosLayout.setVerticalGroup(
            pnlusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlusuariosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Lista De Productos");

        getContentPane().add(pnlusuarios, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (tblInventario.getSelectedRow() > -1) {
            tblInventario.removeRowSelectionInterval(tblInventario.getSelectedRow(), tblInventario.getSelectedRow());
        }
        Memoria.put("accionI", inventarioController.CRUD_NUEVO);
        accionesInventario view = new accionesInventario(null, true);
        view.setVisible(true);
        ic.ListarInventario(tblInventario, "");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (tblInventario.getRowCount() > 0) {
            if (tblInventario.getSelectedRowCount() > 0) {

                modalInventario idInv = new modalInventario();
                int codigo = (int) tblInventario.getValueAt(tblInventario.getSelectedRow(), 0);
                idInv.setIdProducto(codigo);

                Memoria.put("idInv", idInv);
                WarningAlertaI wa = new WarningAlertaI(null, true);
                wa.setVisible(true);
                ic.ListarInventario(tblInventario, "");

                //WarningAlerta.lblMensaje2.setText("¡¡¡COMPLETE TODOS LOS CAMPOS!!!");
                //ErrorAlerta ae = new ErrorAlerta(null, true);
                //ErrorAlerta.lblMensaje2.setText("¡¡¡COMPLETE TODOS LOS CAMPOS!!!");
                //ae.setVisible(true);
            } else {

                ErrorAlerta ae = new ErrorAlerta(null, true);
                ErrorAlerta.lblMensaje2.setText("¡¡¡SELECCIONE UN PRODUCTO!!!");
                ae.setVisible(true);
            }
        } else {
            ErrorAlerta ae = new ErrorAlerta(null, true);
            ErrorAlerta.lblMensaje2.setText("¡¡¡NO HAY PRODUCTOS!!!");
            ae.setVisible(true);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        if (tblInventario.getRowCount() > 0) {
            if (tblInventario.getSelectedRowCount() > 0) {
                int idInventario = (int) tblInventario.getValueAt(tblInventario.getSelectedRow(), 0);
                String producto = (String) tblInventario.getValueAt(tblInventario.getSelectedRow(), 1);
                String categoria = (String) tblInventario.getValueAt(tblInventario.getSelectedRow(), 2);
                String unidad = (String) tblInventario.getValueAt(tblInventario.getSelectedRow(), 3);
                double pCompra = (double) tblInventario.getValueAt(tblInventario.getSelectedRow(), 4);
                double pVenta = (double) tblInventario.getValueAt(tblInventario.getSelectedRow(), 5);
                double stock = (double) tblInventario.getValueAt(tblInventario.getSelectedRow(), 6);
                String fechaV = (String) tblInventario.getValueAt(tblInventario.getSelectedRow(), 7);

                modalInventario mc = new modalInventario(idInventario, producto, pCompra, pVenta, stock, fechaV, categoria, unidad);
//
                Memoria.put("accionI", inventarioController.CRUD_EDITAR);
                Memoria.put("inventario", mc);
                accionesInventario view = new accionesInventario(null, true);

                view.setVisible(true);
                ic.ListarInventario(tblInventario, "");

            } else {

                ErrorAlerta ae = new ErrorAlerta(null, true);
                ErrorAlerta.lblMensaje2.setText("¡¡¡SELECCIONE UNA CATEGORIA!!!");
                ae.setVisible(true);
            }
        } else {
            ErrorAlerta ae = new ErrorAlerta(null, true);
            ErrorAlerta.lblMensaje2.setText("¡¡¡NO HAY CATEGORIAS!!!");
            ae.setVisible(true);
        }


    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        rc.ReporteInventario();

        // System.out.println("codiog: 123456" );b
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void tblInventarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblInventarioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblInventarioKeyReleased

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        if (tblInventario.getSelectedRow() > -1) {
            tblInventario.removeRowSelectionInterval(tblInventario.getSelectedRow(), tblInventario.getSelectedRow());
        }
        String busca = txtbuscar.getText();
        ic.ListarInventario(tblInventario, busca);
        //  System.out.println("Formularios.xd.txtbuscarKeyReleased()");
        //  vc.ListarProducto(tblSelectProducto, busca);
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void btn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3MouseEntered

    private void btn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3MouseExited

    private void btn3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3MousePressed

    private void btn3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3MouseReleased

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        txtbuscar.setText("");
        txtbuscar.requestFocus();
        ic.ListarInventario(tblInventario, "");
    }//GEN-LAST:event_btn3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btn3;
    private rojeru_san.RSButtonRiple btnActualizar;
    private rojeru_san.RSButtonRiple btnAgregar;
    private rojeru_san.RSButtonRiple btnEliminar;
    private rojeru_san.RSButtonRiple btnImprimir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnlusuarios;
    private rojerusan.RSPanelImage rSPanelImage5;
    private javax.swing.JTable tblInventario;
    private app.bolivia.swing.JCTextField txtbuscar;
    // End of variables declaration//GEN-END:variables

}
