/*
 * BENGY JAMMIL AGUILA RUIZ
 * bengyjar1998@outlook.com
 * Facebook: https://www.facebook.com/0101114100d
 * Instagram: https://www.instagram.com/bengijammilaguilaruiz/?hl=es-la
 */
package Formularios;

import Alertas.ErrorAlerta;
import Alertas.ExitoAlerta;
import Controller.ReportesController;
import Controller.clienteController;
import Controller.ventaController;
import Modal.modalVenta;
import Modal.modalUsuario;
import Modal.modalBoleta;
import Modal.modalFactura;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import service.OperacionesVentas;
import util.Memoria;

/**
 *
 * @author Bengy Aguila Ruiz bengyjar1998@outlook.com
 */
public class ventasView extends javax.swing.JInternalFrame {

    ventaController vc = new ventaController();
    clienteController cc = new clienteController();
    OperacionesVentas ov = new OperacionesVentas();
    DecimalFormat formateador = new DecimalFormat("00000");
    ReportesController rc = new ReportesController();

    public ventasView() {
        initComponents();
        tblSelectProductos.getTableHeader().setDefaultRenderer(new util.EstiloTablaHeader());
        tblSelectProductos.setDefaultRenderer(Object.class, new util.EstiloTablaRendererCenter());
        tblSelectProductos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        tblSelectProductos.getColumnModel().getColumn(0).setMaxWidth(0);
        tblSelectProductos.getColumnModel().getColumn(0).setMinWidth(0);
        tblSelectProductos.getColumnModel().getColumn(0).setPreferredWidth(0);

        tblSelectProductos.getColumnModel().getColumn(2).setMinWidth(120);
        tblSelectProductos.getColumnModel().getColumn(2).setMaxWidth(120);

        tblSelectProductos.getColumnModel().getColumn(3).setMinWidth(120);
        tblSelectProductos.getColumnModel().getColumn(3).setMaxWidth(120);

        tblSelectProductos.getColumnModel().getColumn(4).setMinWidth(120);
        tblSelectProductos.getColumnModel().getColumn(4).setMaxWidth(120);

        tblProductosVender.getTableHeader().setDefaultRenderer(new util.EstiloTablaHeader());
        tblProductosVender.setDefaultRenderer(Object.class, new util.EstiloTablaRendererCenter());
        tblProductosVender.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        tblProductosVender.getColumnModel().getColumn(0).setMaxWidth(0);
        tblProductosVender.getColumnModel().getColumn(0).setMinWidth(0);
        tblProductosVender.getColumnModel().getColumn(0).setPreferredWidth(0);

        tblProductosVender.getColumnModel().getColumn(2).setMinWidth(120);
        tblProductosVender.getColumnModel().getColumn(2).setMaxWidth(120);

        tblProductosVender.getColumnModel().getColumn(3).setMinWidth(120);
        tblProductosVender.getColumnModel().getColumn(3).setMaxWidth(120);

        tblProductosVender.getColumnModel().getColumn(4).setMinWidth(120);
        tblProductosVender.getColumnModel().getColumn(4).setMaxWidth(120);

        vc.ListarCategoria(cboCtegoria);
        vc.ListarProducto(tblSelectProductos, "", "");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rSPanelImage2 = new rojerusan.RSPanelImage();
        jLabel3 = new javax.swing.JLabel();
        lblCambio = new javax.swing.JLabel();
        rSPanelImage3 = new rojerusan.RSPanelImage();
        jLabel4 = new javax.swing.JLabel();
        txtImporte = new app.bolivia.swing.JCTextField();
        rSPanelImage6 = new rojerusan.RSPanelImage();
        jSeparator3 = new javax.swing.JSeparator();
        txtcantidad = new app.bolivia.swing.JCTextField();
        btnCantidad = new rojeru_san.RSButtonRiple();
        rSPanelImage5 = new rojerusan.RSPanelImage();
        jSeparator2 = new javax.swing.JSeparator();
        txtbuscarNombre = new app.bolivia.swing.JCTextField();
        btnBuscarNombre = new rojeru_san.RSButtonRiple();
        btnCalcular = new rojeru_san.RSButtonRiple();
        btnAgregar = new rojeru_san.RSButtonRiple();
        jPanel7 = new javax.swing.JPanel();
        txtNombreClienteBoleta = new app.bolivia.swing.JCTextField();
        btn2 = new rojeru_san.RSButtonRiple();
        txtNombreClienteFactura = new app.bolivia.swing.JCTextField();
        cboCtegoria = new rojerusan.RSComboMetro();
        btnRealizarVentas = new rojeru_san.RSButtonRiple();
        btnQuitar = new rojeru_san.RSButtonRiple();
        btnCancelar = new rojeru_san.RSButtonRiple();
        cboTipo = new rojerusan.RSComboMetro();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblIgv = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTotalPagar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblProductosVender = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblSelectProductos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Area de Ventas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagengesVentas/icons8_shopping_cart_96px.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        rSPanelImage2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/ImagengesVentas/VUELTO.png"))); // NOI18N
        rSPanelImage2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 112, 192));
        jLabel3.setText("$");
        rSPanelImage2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        lblCambio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCambio.setForeground(new java.awt.Color(165, 205, 233));
        lblCambio.setText("Cambio...");
        rSPanelImage2.add(lblCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 40));

        rSPanelImage3.setImagen(new javax.swing.ImageIcon(getClass().getResource("/ImagengesVentas/importe.png"))); // NOI18N
        rSPanelImage3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 112, 192));
        jLabel4.setText("$");
        rSPanelImage3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 40));

        txtImporte.setBorder(null);
        txtImporte.setToolTipText("");
        txtImporte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtImporte.setPhColor(new java.awt.Color(0, 112, 192));
        txtImporte.setPlaceholder("Importe...");
        txtImporte.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtImporteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImporteKeyTyped(evt);
            }
        });
        rSPanelImage3.add(txtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 120, 40));

        rSPanelImage6.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelImage6.setImagen(new javax.swing.ImageIcon(getClass().getResource("/ImagengesVentas/cantidad.png"))); // NOI18N
        rSPanelImage6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setBackground(new java.awt.Color(0, 112, 192));
        rSPanelImage6.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 47, 180, 20));

        txtcantidad.setBorder(null);
        txtcantidad.setToolTipText("");
        txtcantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtcantidad.setPhColor(new java.awt.Color(0, 112, 192));
        txtcantidad.setPlaceholder("Cantidad...");
        txtcantidad.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcantidadKeyReleased(evt);
            }
        });
        rSPanelImage6.add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 8, 120, 40));

        btnCantidad.setBackground(new java.awt.Color(255, 255, 255));
        btnCantidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn-cerrar.png"))); // NOI18N
        btnCantidad.setColorHover(new java.awt.Color(31, 174, 255));
        btnCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCantidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCantidadMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCantidadMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCantidadMouseReleased(evt);
            }
        });
        btnCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantidadActionPerformed(evt);
            }
        });
        rSPanelImage6.add(btnCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 8, 35, 35));

        rSPanelImage5.setBackground(new java.awt.Color(255, 255, 255));
        rSPanelImage5.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar_1.png"))); // NOI18N
        rSPanelImage5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(0, 112, 192));
        rSPanelImage5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 47, 180, 20));

        txtbuscarNombre.setBorder(null);
        txtbuscarNombre.setToolTipText("");
        txtbuscarNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtbuscarNombre.setPhColor(new java.awt.Color(0, 112, 192));
        txtbuscarNombre.setPlaceholder("Nombre...");
        txtbuscarNombre.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtbuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarNombreActionPerformed(evt);
            }
        });
        txtbuscarNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarNombreKeyReleased(evt);
            }
        });
        rSPanelImage5.add(txtbuscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 8, 140, 40));

        btnBuscarNombre.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn-cerrar.png"))); // NOI18N
        btnBuscarNombre.setColorHover(new java.awt.Color(31, 174, 255));
        btnBuscarNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarNombreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarNombreMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarNombreMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBuscarNombreMouseReleased(evt);
            }
        });
        btnBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreActionPerformed(evt);
            }
        });
        rSPanelImage5.add(btnBuscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 8, 35, 35));

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagengesVentas/calcular1.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setToolTipText("Calcular el vuelto");
        btnCalcular.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnCalcular.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagengesVentas/calcular.png"))); // NOI18N
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagengesVentas/venta.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setToolTipText("Agregar productos \npara vender");
        btnAgregar.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnAgregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagengesVentas/venta1.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 112, 192), 2));
        jPanel7.setPreferredSize(new java.awt.Dimension(395, 52));
        jPanel7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPanel7KeyTyped(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreClienteBoleta.setBorder(null);
        txtNombreClienteBoleta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNombreClienteBoleta.setPhColor(new java.awt.Color(0, 112, 192));
        txtNombreClienteBoleta.setPlaceholder("Nombre Cliente...");
        txtNombreClienteBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteBoletaActionPerformed(evt);
            }
        });
        txtNombreClienteBoleta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreClienteBoletaKeyReleased(evt);
            }
        });
        jPanel7.add(txtNombreClienteBoleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 2, 220, 40));

        btn2.setBackground(new java.awt.Color(255, 255, 255));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn-cerrar.png"))); // NOI18N
        btn2.setColorHover(new java.awt.Color(31, 174, 255));
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn2MouseReleased(evt);
            }
        });
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel7.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 6, 35, 35));

        txtNombreClienteFactura.setBorder(null);
        txtNombreClienteFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNombreClienteFactura.setPhColor(new java.awt.Color(0, 112, 192));
        txtNombreClienteFactura.setPlaceholder("Nombre Cliente...");
        txtNombreClienteFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreClienteFacturaActionPerformed(evt);
            }
        });
        txtNombreClienteFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreClienteFacturaKeyReleased(evt);
            }
        });
        jPanel7.add(txtNombreClienteFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 2, 220, 40));

        cboCtegoria.setColorArrow(new java.awt.Color(31, 174, 255));
        cboCtegoria.setColorBorde(new java.awt.Color(31, 174, 255));
        cboCtegoria.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboCtegoria.setMinimumSize(new java.awt.Dimension(101, 28));
        cboCtegoria.setPreferredSize(new java.awt.Dimension(200, 41));
        cboCtegoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCtegoriaActionPerformed(evt);
            }
        });

        btnRealizarVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagengesVentas/vender.png"))); // NOI18N
        btnRealizarVentas.setText("Realizar Venta");
        btnRealizarVentas.setToolTipText("Realizar Venta");
        btnRealizarVentas.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnRealizarVentas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagengesVentas/vender1.png"))); // NOI18N
        btnRealizarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarVentasActionPerformed(evt);
            }
        });

        btnQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagengesVentas/venta.png"))); // NOI18N
        btnQuitar.setText("Quitar");
        btnQuitar.setToolTipText("Quitar Producto a \nVender");
        btnQuitar.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnQuitar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagengesVentas/venta1.png"))); // NOI18N
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar1.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar Venta");
        btnCancelar.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Boleta", "Factura" }));
        cboTipo.setColorArrow(new java.awt.Color(31, 174, 255));
        cboTipo.setColorBorde(new java.awt.Color(31, 174, 255));
        cboTipo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboTipo.setMinimumSize(new java.awt.Dimension(101, 28));
        cboTipo.setPreferredSize(new java.awt.Dimension(200, 41));
        cboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rSPanelImage6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(rSPanelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(rSPanelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rSPanelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboCtegoria, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRealizarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSPanelImage6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rSPanelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSPanelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSPanelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCtegoria, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRealizarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Lista de Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 112, 192));
        jLabel6.setText("SUB TOTAL: $");

        lblIgv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIgv.setText("0.0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 112, 192));
        jLabel5.setText("IGV: $");

        lblTotalPagar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotalPagar.setText("0.0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 112, 192));
        jLabel1.setText("TOTAL A PAGAR: $");

        lblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSubTotal.setText("0.0");

        tblProductosVender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblProductosVender.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUCTO", "PRECIO", "CANTIDAD", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductosVender.setGridColor(new java.awt.Color(0, 0, 0));
        tblProductosVender.setRowHeight(20);
        tblProductosVender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblProductosVenderKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tblProductosVender);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8)
                        .addComponent(lblSubTotal)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel5)
                        .addGap(3, 3, 3)
                        .addComponent(lblIgv)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(lblTotalPagar))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lblSubTotal)
                    .addComponent(jLabel5)
                    .addComponent(lblIgv)
                    .addComponent(jLabel1)
                    .addComponent(lblTotalPagar)))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Lista de Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        tblSelectProductos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblSelectProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUCTO", "UD", "PRECIO", "STOCK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSelectProductos.setGridColor(new java.awt.Color(0, 0, 0));
        tblSelectProductos.setRowHeight(20);
        tblSelectProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblSelectProductosKeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(tblSelectProductos);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, "card2");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProductosVenderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblProductosVenderKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProductosVenderKeyReleased

    private void txtbuscarNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarNombreKeyReleased
        if (tblSelectProductos.getSelectedRow() > -1) {
            tblSelectProductos.removeRowSelectionInterval(tblSelectProductos.getSelectedRow(), tblSelectProductos.getSelectedRow());
        }
        String busca = txtbuscarNombre.getText();
        String categoria = cboCtegoria.getSelectedItem().toString();

        if (categoria.equals("Categoria")) {
            vc.ListarProducto(tblSelectProductos, "", busca);
        } else {

            vc.ListarProducto(tblSelectProductos, categoria, busca);
        }
    }//GEN-LAST:event_txtbuscarNombreKeyReleased

    private void btnBuscarNombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarNombreMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarNombreMouseEntered

    private void btnBuscarNombreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarNombreMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarNombreMouseExited

    private void btnBuscarNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarNombreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarNombreMousePressed

    private void btnBuscarNombreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarNombreMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarNombreMouseReleased

    private void btnBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreActionPerformed
        txtbuscarNombre.setText("");
        txtbuscarNombre.requestFocus();
        String categoria = cboCtegoria.getSelectedItem().toString();

        if (categoria.equals("Categoria")) {
            vc.ListarProducto(tblSelectProductos, "", "");
        } else {

            vc.ListarProducto(tblSelectProductos, categoria, "");
        }
        //  vc.ListarProducto(tblProductosVender, categoria, "");
    }//GEN-LAST:event_btnBuscarNombreActionPerformed

    private void txtcantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadKeyReleased

    private void btnCantidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCantidadMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCantidadMouseEntered

    private void btnCantidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCantidadMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCantidadMouseExited

    private void btnCantidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCantidadMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCantidadMousePressed

    private void btnCantidadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCantidadMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCantidadMouseReleased

    private void btnCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantidadActionPerformed
        txtcantidad.setText("");
        txtcantidad.requestFocus();
    }//GEN-LAST:event_btnCantidadActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        DecimalFormatSymbols separadoresPersonalizados = new DecimalFormatSymbols();
        separadoresPersonalizados.setDecimalSeparator('.');
        DecimalFormat formato = new DecimalFormat("#.###", separadoresPersonalizados);

        if (tblSelectProductos.getSelectedRowCount() > 0 && txtcantidad.getText().isEmpty() || txtcantidad.getText().equals("0")) {
            ErrorAlerta ae = new ErrorAlerta(null, true);
            ErrorAlerta.lblMensaje2.setText("¡¡¡AGREGUE UNA CANTIDAD!!!");
            ae.setVisible(true);
        } else if (tblSelectProductos.getSelectedRowCount() > 0) {
            ov.realizarVenta(tblSelectProductos, tblProductosVender, txtcantidad);
            lblTotalPagar.setText(formato.format(ov.acumuladortotal()));
            lblIgv.setText(formato.format((ov.acumuladortotal() * 0.18)));
            lblSubTotal.setText(formato.format((ov.acumuladortotal() - (ov.acumuladortotal() * 0.18))));
            txtcantidad.setText("");
            txtcantidad.requestFocus();
            /// ov.reiniciar();
        } else {
            ErrorAlerta ae = new ErrorAlerta(null, true);
            ErrorAlerta.lblMensaje2.setText("¡¡¡SELECCIONE UN PRODUCTO!!!");
            ae.setVisible(true);
            //ov.mensaje("Seleccione Producto");

        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblSelectProductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSelectProductosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSelectProductosKeyReleased

    private void btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseEntered
        btn2.setBackground(new java.awt.Color(31, 174, 255));
    }//GEN-LAST:event_btn2MouseEntered

    private void btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseExited
        btn2.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btn2MouseExited

    private void btn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2MousePressed

    private void btn2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2MouseReleased

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (cboTipo.getSelectedIndex() == 0) {
            txtNombreClienteBoleta.setText("");
            txtNombreClienteBoleta.requestFocus();
        } else if (cboTipo.getSelectedIndex() == 1) {

            txtNombreClienteFactura.setText("");
            txtNombreClienteFactura.requestFocus();
        }

    }//GEN-LAST:event_btn2ActionPerformed

    private void jPanel7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel7KeyTyped
        char letras = evt.getKeyChar();
        if ((letras < 'a' || letras > 'z') && (letras < 'A' | letras > 'Z')) {
            if ((letras != 'ñ') && (letras != 'Ñ') && (letras != 'á') && (letras != 'Á') && (letras != 'é') && (letras != 'É') && (letras != 'í')
                    && (letras != 'Í') && (letras != 'ó') && (letras != 'Ó') && (letras != 'ú') && (letras != 'Ú') && (letras != '.') && (letras != ' ')) {
                evt.consume();
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7KeyTyped

    private void cboCtegoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCtegoriaActionPerformed
        String categoria = cboCtegoria.getSelectedItem().toString();

        if (categoria.equals("Categoria")) {
            vc.ListarProducto(tblSelectProductos, "", "");
        } else {

            vc.ListarProducto(tblSelectProductos, categoria, "");
        }
    }//GEN-LAST:event_cboCtegoriaActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        DecimalFormatSymbols separadoresPersonalizados = new DecimalFormatSymbols();
        separadoresPersonalizados.setDecimalSeparator('.');
        DecimalFormat formato = new DecimalFormat("#.###", separadoresPersonalizados);

        if (txtImporte.getText().isEmpty()) {

            ErrorAlerta ae = new ErrorAlerta(null, true);
            ErrorAlerta.lblMensaje2.setText("¡¡¡IMPORTE INCORRECTO!!!");
            ae.setVisible(true);

        } else {
            double total = Double.parseDouble(formato.format(ov.acumuladortotal()));
            double calculo = Double.parseDouble(txtImporte.getText());
            if (calculo == 0 || calculo < total) {

                ErrorAlerta ae = new ErrorAlerta(null, true);
                ErrorAlerta.lblMensaje2.setText("¡¡¡IMPORTE INCORRECTO!!!");
                ae.setVisible(true);

            } else {

                lblCambio.setForeground(new java.awt.Color(0, 0, 0));
                lblCambio.setText("" + (calculo - total));
            }
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnRealizarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarVentasActionPerformed
        DecimalFormatSymbols separadoresPersonalizados = new DecimalFormatSymbols();
        separadoresPersonalizados.setDecimalSeparator('.');
        DecimalFormat formato = new DecimalFormat("#.###", separadoresPersonalizados);

        if (tblProductosVender.getRowCount() == 0) {

            ErrorAlerta ae = new ErrorAlerta(null, true);
            ErrorAlerta.lblMensaje2.setText("¡¡¡AGREGUE PRODUCTOS!!!");
            ae.setVisible(true);

        } else if (txtImporte.getText().isEmpty()) {

            ErrorAlerta ae = new ErrorAlerta(null, true);
            ErrorAlerta.lblMensaje2.setText("¡¡¡AGREGUE UN IMPORTE!!!");
            ae.setVisible(true);

        } else {
            double total = Double.parseDouble(formato.format(ov.acumuladortotal()));
            double calculo = Double.parseDouble(txtImporte.getText());
            if (calculo == 0 || calculo < total) {

                ErrorAlerta ae = new ErrorAlerta(null, true);
                ErrorAlerta.lblMensaje2.setText("¡¡¡IMPORTE INCORRECTO!!!");
                ae.setVisible(true);

            } else {
                modalUsuario u = (modalUsuario) Memoria.get("modalUsuario");

                if (cboTipo.getSelectedIndex() == 0) {

                    modalVenta mdV = new modalVenta();
                    int numVenta = Integer.parseInt(vc.NumeroVenta() + "");
                    Memoria.put("numVenta", numVenta);
                    mdV.setIdventa(numVenta);

                    if (vc.insertVenta(mdV)) {
                        //insertBoleta

                        modalBoleta mv = new modalBoleta();
                        //Primer Dato idUser    
                        mv.setIdUsuario(u.getIdUsuario() + "");
                        //Segundo Dato Nventa

                        mv.setIdventa(numVenta);
                        //Tercer Dato Nombre del cliente
                        mv.setNombreCliente(txtNombreClienteBoleta.getText());
                        ///BOLETA

                        if (vc.insertBoleta(mv)) {

                            modalVenta md = new modalVenta();
                            for (int i = 0; i < tblProductosVender.getRowCount(); i++) {

                                md.setnVenta(numVenta);
                                md.setProducto(tblProductosVender.getValueAt(i, 1).toString());
                                md.setCantidad(Double.parseDouble(tblProductosVender.getValueAt(i, 3).toString()));
                                vc.insertDetalleVenta(md);
                            }

                            lblCambio.setForeground(new java.awt.Color(0, 0, 0));
                            lblCambio.setText("" + (calculo - total));

                            DefaultTableModel modelo = (DefaultTableModel) tblProductosVender.getModel();
                            ov.reiniciar();
                            ov.agregar(modelo);

                            txtcantidad.setText("");
                            txtcantidad.requestFocus();
                            txtImporte.setText("");
                            cboCtegoria.setSelectedIndex(0);

                            ExitoAlerta ae = new ExitoAlerta(null, true);
                            ExitoAlerta.lblMensaje1.setText("¡¡¡BOLETA N°" + vc.NumeroVentaBoleta() + "!!!");
                            ExitoAlerta.lblMensaje2.setText("¡¡¡REGISTRADA CON EXITO!!!");
                            ae.setVisible(true);
                            lblSubTotal.setText(formato.format(ov.acumuladortotal()));
                            lblTotalPagar.setText(formato.format((ov.acumuladortotal() * 0.18)));
                            lblIgv.setText(formato.format((ov.acumuladortotal() - (ov.acumuladortotal() * 0.18))));

                            if (txtNombreClienteBoleta.getText().isEmpty()) {
                                rc.ReporteBoleta1(numVenta);
                            } else {
                                rc.ReporteBoleta(numVenta);
                            }

                        }

                    } else {
                        ErrorAlerta ae = new ErrorAlerta(null, true);
                        ErrorAlerta.lblMensaje2.setText("¡¡¡NO SE REALIZO LA VENTA!!!");
                        ae.setVisible(true);
                    }

                } else {
                    ///-------------------------------------------------FACTURA---------------------------------------------//
                    modalVenta mv = new modalVenta();
                    //int numVentaf = Integer.parseInt(formateador.format(vc.NumeroVentaFactura()));
                    int numVentaf = Integer.parseInt(vc.NumeroVenta() + "");
                    Memoria.put("numVenta", numVentaf);
                    mv.setIdventa(numVentaf);

                    String busca = txtNombreClienteFactura.getText();

                    if (txtNombreClienteFactura.getText().isEmpty()) {

                        ErrorAlerta ae = new ErrorAlerta(null, true);
                        ErrorAlerta.lblMensaje2.setText("¡¡¡INGRESE UN CLIENTE!!!");
                        ae.setVisible(true);
                    } else if (!cc.verificaCliente(busca)) {
                        ErrorAlerta ae = new ErrorAlerta(null, true);
                        ErrorAlerta.lblMensaje2.setText("¡¡¡INGRESE UN CLIENTE!!!");
                        ae.setVisible(true);
                    } else {

                        if (vc.insertVenta(mv)) {

                            modalFactura mf = new modalFactura();
                            //Primer Dato idUser
                            mf.setIdUsuario(u.getIdUsuario() + "");
                            //Segundo Dato Cliente
                            mf.setNombreComercialCliente(txtNombreClienteFactura.getText());
                            //Tercer Dato Nventa
                            mf.setIdventa(numVentaf);

                            if (vc.insertFactura(mf)) {

                                modalVenta md = new modalVenta();

                                for (int i = 0; i < tblProductosVender.getRowCount(); i++) {

                                    md.setnVenta(numVentaf);
                                    md.setProducto(tblProductosVender.getValueAt(i, 1).toString());
                                    md.setCantidad(Double.parseDouble(tblProductosVender.getValueAt(i, 3).toString()));
                                    vc.insertDetalleVenta(md);
                                }

                                lblCambio.setForeground(new java.awt.Color(0, 0, 0));
                                lblCambio.setText("" + (calculo - total));

                                DefaultTableModel modelo = (DefaultTableModel) tblProductosVender.getModel();
                                ov.reiniciar();
                                ov.agregar(modelo);

                                txtcantidad.setText("");
                                txtcantidad.requestFocus();
                                txtImporte.setText("");
                                cboCtegoria.setSelectedIndex(0);

                                ExitoAlerta ae = new ExitoAlerta(null, true);
                                ExitoAlerta.lblMensaje1.setText("¡¡¡FACTURA N°" + vc.NumeroVentaFactura() + "!!!");
                                ExitoAlerta.lblMensaje2.setText("¡¡¡REGISTRADA CON EXITO!!!");
                                lblSubTotal.setText(formato.format(ov.acumuladortotal()));
                                lblTotalPagar.setText(formato.format((ov.acumuladortotal() * 0.18)));
                                lblIgv.setText(formato.format((ov.acumuladortotal() - (ov.acumuladortotal() * 0.18))));
                                txtNombreClienteFactura.setText("");
                                ae.setVisible(true);
                                rc.ReporteFactura(numVentaf);

                            } else {
                                ErrorAlerta ae = new ErrorAlerta(null, true);
                                ErrorAlerta.lblMensaje2.setText("¡¡¡NO SE REALIZO LA VENTA!!!");
                                ae.setVisible(true);
                            }

                        }
                    }

                    /* modalFactura mf = new modalFactura();
                    //Primer Dato idUser
                    mf.setIdUsuario(u.getIdUsuario() + "");
                    //Segundo Dato Cliente
                    mf.setNombreComercialCliente(txtNombreClienteFactura.getText());
                    //Tercer Dato Nventa
                    int numFac = Integer.parseInt(formateador.format(vc.NumeroVentaFactura()));
                    Memoria.put("numfactura", numFac);
                    mf.setIdventa(numFac);

                    if (vc.insertFactura(mf)) {

                        modalVenta md = new modalVenta();

                        for (int i = 0; i < tblProductosVender.getRowCount(); i++) {

                            md.setnVenta(numFac);
                            md.setProducto(tblProductosVender.getValueAt(i, 1).toString());
                            md.setCantidad(Double.parseDouble(tblProductosVender.getValueAt(i, 3).toString()));
                            vc.insertVenta(md);
                        }

                        lblCambio.setForeground(new java.awt.Color(0, 0, 0));
                        lblCambio.setText("" + (calculo - total));

                        DefaultTableModel modelo = (DefaultTableModel) tblProductosVender.getModel();
                        ov.reiniciar();
                        ov.agregar(modelo);

                        txtcantidad.setText("");
                        txtcantidad.requestFocus();
                        txtImporte.setText("");
                        cboCtegoria.setSelectedIndex(0);

                        rc.ReporteFactura(numFac);
                        ExitoAlerta ae = new ExitoAlerta(null, true);
                        ExitoAlerta.lblMensaje1.setText("¡¡¡FACTURA N°" + numFac + "!!!");
                        ExitoAlerta.lblMensaje2.setText("¡¡¡REGISTRADA CON EXITO!!!");
                        ae.setVisible(true);

                    }*/ {

                    }
                }

            }
        }
    }//GEN-LAST:event_btnRealizarVentasActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        DecimalFormatSymbols separadoresPersonalizados = new DecimalFormatSymbols();
        separadoresPersonalizados.setDecimalSeparator('.');
        DecimalFormat formato = new DecimalFormat("#.###", separadoresPersonalizados);
        DefaultTableModel modelo = (DefaultTableModel) tblProductosVender.getModel();

        if (modelo.getRowCount() > 0) {

            int fila = tblProductosVender.getSelectedRow();
            //Verificamos que se halla seleccionado un registro
            //Si no se a seleccionado, mandamos mensaje
            if (tblProductosVender.getSelectedRowCount() < 1) {

                ErrorAlerta ae = new ErrorAlerta(null, true);
                ErrorAlerta.lblMensaje2.setText("¡¡¡SELECCIONE UN REGISTRO!!!");
                ae.setVisible(true);
                // ov.mensaje("Seleccione un Registro");

            } else {

                String buscar = tblProductosVender.getValueAt(fila, 1).toString();
                //double dis = Double.parseDouble(tblProductosVender.getValueAt(fila, 3).toString());
                int numero = ov.disminuirStock(buscar);
                ov.eliminar(numero);
                ov.agregar(modelo);

                lblTotalPagar.setText(formato.format(ov.acumuladortotal()));
                lblIgv.setText(formato.format((ov.acumuladortotal() * 0.18)));
                lblSubTotal.setText(formato.format((ov.acumuladortotal() - (ov.acumuladortotal() * 0.18))));
                txtcantidad.setText("");
                txtcantidad.requestFocus();
                //modelo.removeRow(fila);
            }

        } else //Si no hay, mandamos mensaje
        {

            ErrorAlerta ae = new ErrorAlerta(null, true);
            ErrorAlerta.lblMensaje2.setText("¡¡¡NO HAY REGISTROS!!!");
            ae.setVisible(true);
        }
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        DecimalFormatSymbols separadoresPersonalizados = new DecimalFormatSymbols();
        separadoresPersonalizados.setDecimalSeparator('.');
        DecimalFormat formato = new DecimalFormat("#.###", separadoresPersonalizados);
        DefaultTableModel modelo = (DefaultTableModel) tblProductosVender.getModel();
        ov.reiniciar();
        ov.agregar(modelo);
        lblSubTotal.setText(formato.format(ov.acumuladortotal()));
        lblTotalPagar.setText(formato.format((ov.acumuladortotal() * 0.18)));
        lblIgv.setText(formato.format((ov.acumuladortotal() - (ov.acumuladortotal() * 0.18))));
        txtcantidad.setText("");
        txtcantidad.requestFocus();
        lblCambio.setForeground(new java.awt.Color(165, 205, 233));
        lblCambio.setText("CAMBIO");
        txtImporte.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtImporteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImporteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImporteKeyReleased

    private void txtImporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImporteKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))
                && (caracter != KeyEvent.VK_BACK_SPACE)
                && (caracter != '.' || txtImporte.getText().contains("."))) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtImporteKeyTyped

    private void txtbuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarNombreActionPerformed

    private void cboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoActionPerformed
        if (cboTipo.getSelectedIndex() == 0) {

            txtNombreClienteFactura.setVisible(false);
            txtNombreClienteBoleta.setVisible(true);
            txtNombreClienteFactura.setText("");

        } else if (cboTipo.getSelectedIndex() == 1) {
            txtNombreClienteFactura.setVisible(true);
            txtNombreClienteBoleta.setVisible(false);
            txtNombreClienteBoleta.setText("");

        }
    }//GEN-LAST:event_cboTipoActionPerformed

    private void txtNombreClienteBoletaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreClienteBoletaKeyReleased


    }//GEN-LAST:event_txtNombreClienteBoletaKeyReleased

    private void txtNombreClienteBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteBoletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteBoletaActionPerformed

    private void txtNombreClienteFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreClienteFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreClienteFacturaActionPerformed

    private void txtNombreClienteFacturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreClienteFacturaKeyReleased

        try {

            int busca = Integer.parseInt(txtNombreClienteFactura.getText());
            // String busca2 = txtNombreClienteFactura.getText();
            vc.listarCliente2(txtNombreClienteFactura, Integer.toString(busca));
            // TODO1
        } catch (NumberFormatException e) {
            String busca = txtbuscarNombre.getText();
            vc.listarCliente(txtNombreClienteFactura, busca);
        }
        /*
        String busca = txtbuscarNombre.getText();

        if (isNumeric(txtbuscarNombre.getText())) {
            //System.out.println("es ");
            vc.listarCliente2(txtNombreClienteFactura, busca);
        } else {
            vc.listarCliente(txtNombreClienteFactura, busca);
        }*/
    }//GEN-LAST:event_txtNombreClienteFacturaKeyReleased

    public static boolean isNumeric(String cadena) {

        boolean resultado;

        try {
            Integer.parseInt(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btn2;
    private rojeru_san.RSButtonRiple btnAgregar;
    private rojeru_san.RSButtonRiple btnBuscarNombre;
    private rojeru_san.RSButtonRiple btnCalcular;
    private rojeru_san.RSButtonRiple btnCancelar;
    private rojeru_san.RSButtonRiple btnCantidad;
    private rojeru_san.RSButtonRiple btnQuitar;
    private rojeru_san.RSButtonRiple btnRealizarVentas;
    private rojerusan.RSComboMetro cboCtegoria;
    private rojerusan.RSComboMetro cboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblIgv;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTotalPagar;
    private rojerusan.RSPanelImage rSPanelImage2;
    private rojerusan.RSPanelImage rSPanelImage3;
    private rojerusan.RSPanelImage rSPanelImage5;
    private rojerusan.RSPanelImage rSPanelImage6;
    private javax.swing.JTable tblProductosVender;
    private javax.swing.JTable tblSelectProductos;
    private app.bolivia.swing.JCTextField txtImporte;
    private app.bolivia.swing.JCTextField txtNombreClienteBoleta;
    private app.bolivia.swing.JCTextField txtNombreClienteFactura;
    private app.bolivia.swing.JCTextField txtbuscarNombre;
    private app.bolivia.swing.JCTextField txtcantidad;
    // End of variables declaration//GEN-END:variables
}
